### ISSUE TITLE
Image tags not rendering

### ISSUE THREAD

**Issue by aalemayhu** [brumm/whatsgit#3]
Below is a screenshot which shows the issue. I was expecting to see the images inline like Github does.

<img width="707" alt="screen shot 2016-06-06 at 11 30 44" src="https://cloud.githubusercontent.com/assets/925044/15817909/a8e849c8-2bda-11e6-8198-70a85366fdc0.png">

Thanks for making this.

**Comment by brumm** [comment]
> Thanks for making this.

Thanks for using this!

I enabled html support for the markdown renderer, so <img> tags and bountysource plugin markup should be rendered correctly now.
