### ISSUE TITLE
Not all repos are displayed in the inbox

### ISSUE THREAD

**Issue by vorg** [brumm/whatsgit#5]
Are there any limits in the UI or Github API that preven all repos from being displayed?

<img width="211" alt="screen shot 2016-07-21 at 10 21 10" src="https://cloud.githubusercontent.com/assets/171001/17017798/bb1ef022-4f2c-11e6-9519-f60d10f53737.png">

This repo is missing http://github.com/vorg/ideas beside having 9 open issues.

**Comment by brumm** [comment]
Yeah, there are definitely limits. Currently, I'm fetching just the first page with 100 issues.

Note that I'm not fetching issues per-repo but more generally via the `involves` issue search. so github may just sort these issues somewhere near the bottom.

I should probably fetch issues for the user's own repos explicitly and just use the results from involves for additional scoring and sorting. 

In general, proper pagination will be done after some heavy refactoring of the redux storage.

**Comment by brumm** [comment]
Hey @vorg,
I went ahead and pushed out https://github.com/brumm/whatsgit/releases/tag/v0.1.7 which increases the amount of issues being fetched (quickfix before I tackle pagination). Let me know whether this works for you!

**Comment by brumm** [comment]
pushed a new build to fix some styles that went missing during an earlier refactor:
https://github.com/brumm/whatsgit/releases/tag/v0.1.8

**Comment by brumm** [comment]
Gonna close this for now, feel free to reopen if you're still having issues.
